version: '3'

services:
  front:
    ports:
      - 8100:80
    build: ./front
    volumes:
      - ./front/:/usr/local/apache2/htdocs
  api:
    ports:
      - 8101:80
    build: ./api
    volumes:
      - ./api/:/var/www/html
